if(!window.requestAnimationFrame)window.requestAnimationFrame=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();
var mm3d={EPSILON:1.0E-4,baseHeight:0.5,LINEAR_GRADIENT:0,PAN_TOP:4,PAN_LEFT:1,PAN_RIGHT:2,PAN_DOWN:3,ANI_SCALE_BAR:0,sortData:function(a,b){return-a.data+b.data},mouseState:{down:!1,keyDown:!1,zoomIn:!0,pan:0,last:{x:0,y:0},cur:{x:0,y:0}}};
mm3d.ChineseMap=function(a,b,c){if(typeof a!=="object")throw{message:"Cannot intialize with null container."};else this._vp=a;this._option={size:[window.innerWidth,window.innerHeight],colorModel:{type:mm3d.LINEAR_GRADIENT,start:new THREE.Color(16776960),end:new THREE.Color(16711680),stops:[]},showLegend:!0};this.title="";this.minVal=this.maxVal=0;this._modelChanged=!1;this._data={};this._data.model={Zhejiang:{data:0,last:0},Jiangsu:{data:0,last:0},Shandong:{data:0,last:0},Anhui:{data:0,last:0},Shanghai:{data:0,
last:0},Hebei:{data:0,last:0},Jiangxi:{data:0,last:0},Henan:{data:0,last:0},Hainan:{data:0,last:0},Taiwan:{data:0,last:0},Hunan:{data:0,last:0},Sichuan:{data:0,last:0},Yunnan:{data:0,last:0},Gansu:{data:0,last:0},Xizang:{data:0,last:0},Liaoning:{data:0,last:0},Jilin:{data:0,last:0},Heilongjiang:{data:0,last:0},Hubei:{data:0,last:0},Shaanxi:{data:0,last:0},Neimenggu:{data:0,last:0},Guangxi:{data:0,last:0},Qinghai:{data:0,last:0},Ningxia:{data:0,last:0},Xinjiang:{data:0,last:0},Chongqing:{data:0,last:0},
Shanxi:{data:0,last:0},Tianjing:{data:0,last:0},Beijing:{data:0,last:0},Guangdong:{data:0,last:0},Guizhou:{data:0,last:0},Hongkong:{data:0,last:0},Macau:{data:0,last:0},Fujian:{data:0,last:0}};this._data.length=function(a){var b=0,c;for(c in a)b++;return function(){return b}}(this._data.model);if(typeof c==="object")this._option.size=c.size instanceof Array?c.size:this._option.size,this._option.showLegend=typeof c.showLegend==="boolean"?c.showLegend:this._option.showLegend,this._option.colorModel=
typeof c.colorModel==="object"?c.colorModel:this._option.colorModel,this.title=typeof c.title==="string"?c.title:this.title,this._aniStatus.isRun=typeof c.animate==="boolean"?c.animate:!1,this._aniStatus.maxStep=this._aniStatus.isRun?typeof c.animateStep==="number"?c.animateStep:100:this._aniStatus.step=100;b!==void 0&&this._changeData(b);this._calMax();this._lookAtPos={x:0,y:0,z:0}};
mm3d.ChineseMap.prototype={_listeners:{load:[]},addEventListener:function(a,b){this._listeners[a].push(b)},_loadComplete:!1,_calMax:function(){this.maxVal=0;for(var a in this._data.model)this.maxVal=this._data.model[a].data>this.maxVal?this._data.model[a].data:this.maxVal;this._maxbarHeight=this.maxVal>39.125?39.125:this.maxVal;if(this.maxVal===0)this._maxbarHeight=this.maxVal=1},_calColor:function(a){a/=this._maxbarHeight;var b=this._option.colorModel.start,c=this._option.colorModel.end,d=new THREE.Color(0);
d.setRGB(a*(c.r-b.r)+b.r,a*(c.g-b.g)+b.g,a*(c.b-b.b)+b.b);return d},_initLoading:function(){this._loadingNode=document.createElement("div");this._loadingNode.id="mm3dLoading";this._loadingNode.style.width=this._option.size[0]+"px";this._loadingNode.style.height=this._option.size[1]+"px";var a=document.createElement("div");a.className="mm3dLoadingTitle";a.innerHTML="LOADING ...";var b=document.createElement("div");b.className="mm3dLoadingContent";this._loadingNode.changeContent=function(){return function(a){b.innerHTML=
a}}(b);this._loadingNode.appendChild(a);this._loadingNode.appendChild(b);this._vp.appendChild(this._loadingNode);a.style.top=(this._option.size[1]-parseInt(a.clientHeight))*0.5+"px";b.style.top=(this._option.size[1]+parseInt(a.clientHeight))*0.5+"px"},_initCamCtrl:function(){this._camNode=document.createElement("div");this._camNode.id="mm3dCamContainer";for(var a=Math.sqrt(2),a=[{pos:[2*a-1,a-1],sign:mm3d.PAN_TOP},{pos:[a-1,2*a-1],sign:mm3d.PAN_LEFT},{pos:[3*a-1,2*a-1],sign:mm3d.PAN_RIGHT},{pos:[2*
a-1,3*a-1],sign:mm3d.PAN_DOWN}],b=0;b<a.length;b++){var c=document.createElement("div");c.className="mm3dCamButton";c.style.left=18*a[b].pos[0]+"px";c.style.top=18*a[b].pos[1]+"px";c.addEventListener("mousedown",function(a){return function(){mm3d.mouseState.pan=a;mm3d.mouseState.down=!0}}(a[b].sign),!1);c.addEventListener("mouseup",function(){mm3d.mouseState.down=!1},!1);this._camNode.appendChild(c)}this._vp.appendChild(this._camNode)},_repaintLegend:function(){for(;this._legendContext.childNodes.length>
0;)this._legendContext.removeChild(this._legendContext.firstChild);for(var a in this._data.model){var b=document.createElement("div");b.className="mm3dLegendItem";var c=document.createElement("span");c.className="mm3dLegendColor";c.style.backgroundColor=this._calColor(this._data.model[a].data*this._maxbarHeight/this.maxVal).getContextStyle();var d=document.createElement("span");d.className="mm3dLegendName";d.innerHTML=a;var e=document.createElement("span");e.className="mm3dLegendValue";e.innerHTML=
this._data.model[a].data;b.appendChild(c);b.appendChild(d);b.appendChild(e);this._legendContext.appendChild(b)}},_initLegend:function(){var a=document.createElement("div");a.id="mm3dLegendContainer";document.createElement("div").className="mm3dLegendToolbar";var b=document.createElement("div");b.id="mm3dLegend";b.style.height=parseInt(this._option.size[1]/3/30)*30+"px";this._legendContext=document.createElement("div");this._legendContext.id="mm3dLegendCtx";this._repaintLegend();b.appendChild(this._legendContext);
a.appendChild(b);this._vp.appendChild(a)},_mkTitle:function(){this._titleNode===void 0?(this._titleNode=document.createElement("div"),this._titleNode.id="mm3dTitle",this._titleNode.innerHTML=this.title,this._vp.appendChild(this._titleNode)):this._titleNode.innerHTML=this.title},_aniStatus:{isRun:!1,step:0,maxStep:100,type:0},setTitle:function(a){this.title=a;this._mkTitle()},init:function(){var a=document.createElement("div"),b=document.createElement("span"),c=function(a,b){for(attr in b)a[attr]=
b[attr]};this._vp.addEventListener("mousedown",function(){mm3d.mouseState.down=!0},!1);this._vp.addEventListener("mouseup",function(){mm3d.mouseState.down=!1;mm3d.mouseState.pan=0},!1);this._vp.addEventListener("mousemove",function(a){mm3d.mouseState.last=mm3d.mouseState.cur;mm3d.mouseState.cur={x:a.clientX,y:a.clientY}},!1);window.addEventListener("keydown",function(a){switch(a.which){case 65:mm3d.mouseState.keyDown=!0;mm3d.mouseState.zoomIn=!0;break;case 90:mm3d.mouseState.keyDown=!0,mm3d.mouseState.zoomIn=
!1}},!1);window.addEventListener("keyup",function(){mm3d.mouseState.keyDown=!1},!1);var d=a.cloneNode(!0);c(d,{id:"mm3dToolBox",className:"mm3dToolBox"});var e=b.cloneNode(!0);c(e,{id:"mm3dOption",innerHTML:"option",className:"mm3dMenuItem"});e.addEventListener("click",function(){alert("option")},!1);var f=b.cloneNode(!0);c(f,{id:"mm3dHelp",innerHTML:"help",className:"mm3dMenuItem"});f.addEventListener("click",function(){alert("help")},!1);var g=b.cloneNode(!0);c(g,{id:"mm3dExport",innerHTML:"export",
className:"mm3dMenuItem"});g.addEventListener("click",function(){alert("export")},!1);d.appendChild(g);d.appendChild(e);d.appendChild(f);this._vp.appendChild(d);e=a.cloneNode(!0);c(e,{id:"mm3dScaleRuleCont"});this._scaleRule=e;f=a.cloneNode(!0);a=this._option.size[0]/3.9;d=this._option.size[1]/18;c(f,{id:"mm3dScaleRule"});f.style=f.style===void 0?{}:f.style;c(f.style,{width:a+"px",height:d+"px"});g=document.createElement("canvas");g.width=a;g.height=d;f.appendChild(g);this._minTag=b.cloneNode(!0);
this._minTag.innerHTML=this.minVal;c(this._minTag,{id:"mm3dMinTag",className:"mm3dScaleTag"});this._maxTag=b.cloneNode(!0);this._maxTag.innerHTML=this.maxVal;c(this._maxTag,{id:"mm3dMaxTag",className:"mm3dScaleTag"});e.appendChild(this._minTag);e.appendChild(this._maxTag);e.appendChild(f);this._vp.appendChild(e);b=g.getContext("2d");c=b.createLinearGradient(0,0,a,d);c.addColorStop(0,this._option.colorModel.start.getContextStyle());c.addColorStop(1,this._option.colorModel.end.getContextStyle());b.fillStyle=
c;b.fillRect(0,0,a,d);this._initLoading();this._initLegend();this._initCamCtrl();this._mkTitle();this._three={scene:new THREE.Scene,renderer:new THREE.WebGLRenderer({clearColor:0,clearAlpha:1}),camera:new THREE.PerspectiveCamera(75,this._option.size[0]/this._option.size[1],1,1E4),loader:new THREE.JSONLoader(!0),light:new THREE.PointLight(16777215)};this._three.camera.position.set(0,5,0);this._three.camera.up={x:0,y:0,z:-1};this._three.camera.lookAt(this._lookAtPos);this._three.scene.add(this._three.camera);
this._three.light.position.set(0,5,0);this._three.scene.add(this._three.light);this._three.renderer.setSize(this._option.size[0],this._option.size[1]);this._three.scene.add(this._three.camera);this._loadedMesh=[];this._renderScene=function(){if(this._aniStatus.isRun){var a=this._aniStatus;this._aniStatus.step+=1;a.step>=a.maxStep?(a.step=0,this._aniStatus.isRun=!1):this._animator()}if(this._modelChanged)this._repaintModel(),this._maxTag.innerHTML=this.maxVal;if(mm3d.mouseState.down)if(mm3d.mouseState.pan!==
0){switch(mm3d.mouseState.pan){case mm3d.PAN_TOP:this._three.camera.position.z-=0.05;this._lookAtPos.z-=0.05;break;case mm3d.PAN_DOWN:this._three.camera.position.z+=0.05;this._lookAtPos.z+=0.05;break;case mm3d.PAN_RIGHT:this._three.camera.position.x+=0.05;this._lookAtPos.x+=0.05;break;case mm3d.PAN_LEFT:this._three.camera.position.x-=0.05,this._lookAtPos.x-=0.05}this._three.camera.lookAt(this._lookAtPos)}else{var b=mm3d.mouseState.cur.y-mm3d.mouseState.last.y,a=-mm3d.mouseState.cur.x+mm3d.mouseState.last.x;
if(Math.abs(b)>mm3d.EPSILON||Math.abs(a)>mm3d.EPSILON)for(h in b=b*0.5*Math.PI/this._option.size[1],a=a*0.5*Math.PI/this._option.size[0],this._data.model)this._data.model[h].mesh.rotation.x+=b,this._data.model[h].mesh.rotation.z+=a}else if(mm3d.mouseState.keyDown)console.log("asfd"),a=this._three.camera.position,b={x:this._lookAtPos.x-a.x,y:this._lookAtPos.y-a.y,z:this._lookAtPos.z-a.z},mm3d.mouseState.zoomIn?(a.x+=b.x*0.0050,a.y+=b.y*0.0050,a.z+=b.z*0.0050,this._lookAtPos.x+=b.x*0.0050,this._lookAtPos.y+=
b.y*0.0050,this._lookAtPos.z+=b.z*0.0050):(a.x-=b.x*0.0050,a.y-=b.y*0.0050,a.z-=b.z*0.0050,this._lookAtPos.x-=b.x*0.0050,this._lookAtPos.y-=b.y*0.0050,this._lookAtPos.z-=b.z*0.0050),this._three.camera.position=a,this._three.camera.lookAt(this._lookAtPos);this._three.renderer.render(this._three.scene,this._three.camera)};this._mainloop=function(a){return function(){requestAnimationFrame(a._mainloop(a));a._renderScene()}};var b=this._data.length(),h;for(h in this._data.model)(function(a,b,c){a._three.loader.load({model:"js/map"+
b+".js",callback:function(d){a._loadedMesh.push(b);a._data.model[b].mesh=new THREE.Mesh(d,new THREE.MeshLambertMaterial({color:a._calColor(a._data.model[b].data/a.maxVal*a._maxbarHeight).getHex(),transparent:!0}));a._three.scene.add(a._data.model[b].mesh);a._loadingNode.changeContent("Mesh "+b+" loaded. "+a._loadedMesh.length/c*100+"%");if(a._loadedMesh.length>=c){console.log("loads complete.");a._loadComplete=!0;for(d=0;d<a._listeners.load.length;d++)a._listeners.load[d].call();a._vp.removeChild(a._loadingNode);
a._aniStatus.isRun||a._animator();a._mainloop(a)()}}})})(this,h,b);this._three.renderer.domElement.id="mm3dViewport";this._vp.appendChild(this._three.renderer.domElement)},_repaintModel:function(){for(var a in this._data.model)this._data.model[a].mesh.material=new THREE.MeshLambertMaterial({color:this._calColor(this._data.model[a].data/this.maxVal*this._maxbarHeight).getHex(),transparent:!0});this._modelChanged=!1},_animator:function(){if(this._loadComplete)for(var a in this._data.model){var b=this._data.model[a],
c=b.last;b.mesh.scale.y=1+(c+(b.data-c)*this._aniStatus.step/this._aniStatus.maxStep)/this.maxVal*this._maxbarHeight}},change:function(){},_changeData:function(a){for(var b in a){this._data.model[b].last=this._data.model[b].data;for(var c in a[b])this._data.model[b][c]=a[b][c]}this._calMax();this._modelChanged=!0},changeData:function(a,b){this._changeData(a);b===void 0?this._aniStatus.maxStep=this._aniStatus.step=100:(this._aniStatus.step=0,this._aniStatus.isRun=!0,this._aniStatus.maxStep=b.step===
void 0?100:b.step);this._animator()},changeScale:function(a,b,c){this._maxbarHeight=a;if(!this._loadComplete)return!1;if(!this._aniStatus.isRun)return b===void 0||b===!1?this._aniStatus.step=this._aniStatus.maxStep=100:(this._aniStatus.isRun=!0,this._aniStatus.step=0,this._aniStatus.maxStep=typeof c==="number"?c:100),this._animator(),!0;return!1}};
